### PR TITLE
[IA-2235] Install shiny in the RStudio base image

### PR DESCRIPTION
**Pull request by rtitle**
https://broadworkbench.atlassian.net/browse/IA-2235

Based on manual testing this seems to fix RShiny. I'm building the base+bioconductor images locally to confirm. Will update this PR with results.

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]
👍

**Comment by gpcarr** [comment]
Couple of comments:
- we'll need to update the `VERSION` file under both the `anvil-rstudio-base` (https://github.com/anvilproject/anvil-docker/blob/master/anvil-rstudio-base/VERSION#L1 )and `anvil-rstudio-bioconductor` (https://github.com/anvilproject/anvil-docker/blob/master/anvil-rstudio-bioconductor/VERSION#L1) folders as well to match these new versions 
- we'll need to PR to `terra-docker` updating the version of `anvil-rstudio-bioconductor` once the changes in this PR are released (https://github.com/DataBiosphere/terra-docker/blob/master/config/community_images.json#L14)

**Comment by rtitle** [comment]
Thanks for the tips @gpcarr! I'll do that.

Btw, I built and pushed `us.gcr.io/anvil-gcr-public/anvil-rstudio-bioconductor:0.0.7-SNAP` from this branch, deployed it in Terra, and RShiny works! So I think I'll go ahead and try to get this pushed through for next week's release. (cc @nturaga )

**Comment by rtitle** [comment]
Pic of it working (this displayed "Connection Refused" before):

image

**Comment by rtitle** [comment]
Any concerns with this @nturaga  -- OK to merge?

**Comment by nturaga** [comment]
Yep. Please merge it. +1

**Pull request merged**
