### PR TITLE
IA-1998 persist user intalled pip and R packages

### PR DESCRIPTION
**Pull request by gpcarr**
This PR adds environment variables `R_LIBS` and `PIP_USER` to the base and bioconductor images. We are now installing user installed pip to `/home/rstudio` by setting `PIP_USER` to `true` and we are now installing R user installed packages to `/home/rstudio/packages` by adding this dir to `R_LIBS`

This PR also fixes the error in the base image where a user tries to run `pip install some_package` and gets error that they don't have permission to run pip install and should use `--user` when running pip install.

### CODE REVIEW

**Comment by gpcarr** [comment]
depends on https://github.com/DataBiosphere/leonardo/pull/1493 being merged first

**Comment by gpcarr** [comment]
Once this is released, we're going to want to update some of the READMEs to reflect data persistence

**Comment by nturaga** [comment]
@gpcarr I'm guessing this is done? 

> depends on [DataBiosphere/leonardo#1493](https://github.com/DataBiosphere/leonardo/pull/1493) being merged first

**Review by nturaga — APPROVED** [review]

**Comment by gpcarr** [comment]
> @gpcarr I'm guessing this is done?
> 
> > depends on [DataBiosphere/leonardo#1493](https://github.com/DataBiosphere/leonardo/pull/1493) being merged first

yep, merged it this morning. Also just added a comment about how we are mounting the persistent disk and how it affects image installations

**Comment by nturaga** [comment]
Great! Thanks. Will @rtitle review it as well, or should I merge?

**Review by rtitle — APPROVED** [review]
LGTM

Note that after merge the new images will need to be built manually and pushed to GCR. This page has instructions: https://broadworkbench.atlassian.net/wiki/spaces/IA/pages/117080065/AnVIL+Docker+Stack

**Comment by nturaga** [comment]
> LGTM
> 
> Note that after merge the new images will need to be built manually and pushed to GCR. This page has instructions: https://broadworkbench.atlassian.net/wiki/spaces/IA/pages/117080065/AnVIL+Docker+Stack

Great! Can @gpcarr do this? does she have the required permissions to push to the GCR?

**Comment by gpcarr** [comment]
> > LGTM
> > Note that after merge the new images will need to be built manually and pushed to GCR. This page has instructions: https://broadworkbench.atlassian.net/wiki/spaces/IA/pages/117080065/AnVIL+Docker+Stack
> 
> Great! Can @gpcarr do this? does she have the required permissions to push to the GCR?

I pushed test images so I should have permissions. I'll do that today!

**Pull request merged**
